# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17077e0a4a3e49374097edfd720dcdcb2181cb203d21fb1c5d898e3c679ecff4a17b12db247430bf8aeeeba6d424d820e511b9258a9071b62621f3dd302e69c3

test:
  secret_key_base: 8fc1015e23359796eee931f50933c2f6aead37ecbcceab51f9b1e683da4a5b0be814f2f25f65e4682ab8f293ad5328eac36e1f4ad5445834326400f4ffaf8f77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
